import {
  CMMCAssessmentObjectivesPage,
  CMMCAuditReadinessPage,
  CMMCAuditorPage,
  CMMCControlsPage,
  CMMCDomainPage,
  CMMCDomainSummaryPage,
  CMMCEvidenceMappingPage,
  CMMCEvidencePage,
  CMMCExportCenterPage,
  CMMCGapWizardPage,
  CMMCOrganizationPage,
  CMMCOverviewPage,
  CMMCPOAMPage,
  CMMCPoliciesPage,
  CMMCProgressTrackingPage,
  CMMCReadinessScorePage,
  CMMCReviewStatusPage,
  CMMCRiskTrackingPage,
  CMMCScopePage,
  CMMCSPRSScorePage,
  CMMCSSPPage,
} from "./pages";

export const cmmcWorkspaceRoutes = [
  { path: "/cmmc", Component: CMMCScopePage },
  { path: "/cmmc/scope", Component: CMMCScopePage },
  { path: "/cmmc/overview", Component: CMMCOverviewPage },
  { path: "/cmmc/organization", Component: CMMCOrganizationPage },
  { path: "/cmmc/gap-wizard", Component: CMMCGapWizardPage },
  { path: "/cmmc/auditor", Component: CMMCAuditorPage },
  { path: "/cmmc/evidence", Component: CMMCEvidencePage },
  { path: "/cmmc/ssp", Component: CMMCSSPPage },
  { path: "/cmmc/poam", Component: CMMCPOAMPage },
  { path: "/cmmc/policies", Component: CMMCPoliciesPage },
  { path: "/cmmc/domains", Component: CMMCDomainSummaryPage },
  { path: "/cmmc/domains/:domainId", Component: CMMCDomainPage },
  { path: "/cmmc/controls", Component: CMMCControlsPage },
  { path: "/cmmc/assessment-objectives", Component: CMMCAssessmentObjectivesPage },
  { path: "/cmmc/progress", Component: CMMCProgressTrackingPage },
  { path: "/cmmc/readiness-score", Component: CMMCReadinessScorePage },
  { path: "/cmmc/sprs-score", Component: CMMCSPRSScorePage },
  { path: "/cmmc/audit-readiness", Component: CMMCAuditReadinessPage },
  { path: "/cmmc/evidence-mapping", Component: CMMCEvidenceMappingPage },
  { path: "/cmmc/risks", Component: CMMCRiskTrackingPage },
  { path: "/cmmc/review-status", Component: CMMCReviewStatusPage },
  { path: "/cmmc/export-center", Component: CMMCExportCenterPage },
];
